blueprint:
  name: ZHA - IKEA Tradfri Shortcut button 2
  description: Control anything with the ikea shortcut button
  domain: automation
  input:
    shortcut_button:
      name: Device
      description: Select an IKEA shortcut button
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI SHORTCUT Button
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            - domain:
                - light
  # source_url: https://community.home-assistant.io/t/zha-ikea-tradfri-shortcut-button/261936
mode: single
max_exceeded: silent
variables:
  light_input: !input light
  input_entity_id: "{{ light_input.entity_id }}"
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input shortcut_button
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      is_turned_on: "{{ is_state(input_entity_id, 'on') }}"
  - choose:
      # short click
      - conditions:
          - "{{ endpoint_id == 1 }}"
          - "{{ cluster_id == 6 }}"
          - "{{ command == 'on' }}"
        sequence:
          - choose:
              - conditions: "{{ is_turned_on }}"
                sequence:
                  - service: light.turn_off
                    target: !input "light"
                    data:
                      transition: 1
            default:
              - service: light.turn_on
                target: !input "light"
                data:
                  transition: 1
      # long click
      - conditions:
          - "{{ endpoint_id == 1 }}"
          - "{{ cluster_id == 8 }}"
          - "{{ command == 'stop_with_on_off' }}"
        sequence:
          - service: light.turn_on
            target: !input light
            data:
              brightness_step_pct: -20
              transition: 1
