blueprint:
  name: ZHA - IKEA Tradfri Shortcut button
  description: Control anything with the ikea shortcut button
  domain: automation
  input:
    shortcut_button:
      name: Device
      description: Select an IKEA shortcut button
      selector:
        device:
          integration: zha
          manufacturer: IKEA of Sweden
          model: TRADFRI SHORTCUT Button
    light:
      name: Light(s)
      description: The light(s) to control
      selector:
        target:
          entity:
            - domain:
                - light
  source_url: https://github.com/evorgevol/hassio/blob/main/ZHA%20-%20IKEA%20Tradfri%20Shortcut.yaml
mode: single
max_exceeded: silent
variables:
  light_input: !input light
  input_entity_id: "{{ light_input.entity_id }}"
trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input shortcut_button
action:
  - variables:
      command: "{{ trigger.event.data.command }}"
      cluster_id: "{{ trigger.event.data.cluster_id }}"
      endpoint_id: "{{ trigger.event.data.endpoint_id }}"
      is_turned_on: "{{ is_state(input_entity_id, 'on') }}"
  - choose:
      # short click
      - conditions:
          - "{{ endpoint_id == 1 }}"
          - "{{ cluster_id == 6 }}"
          - "{{ command == 'on' }}"
        sequence:
          # check for a second click
          - wait_for_trigger:
              - platform: event
                event_type: zha_event
                event_data:
                  device_id: !input shortcut_button
                  endpoint_id: 1
                  cluster_id: 6
                  command: "on"
            timeout:
              milliseconds: 600
            continue_on_timeout: true
          - choose:
              # if single click
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.trigger }}"
                sequence:
                  - choose:
                      - conditions: "{{ is_turned_on }}"
                        sequence:
                          - service: light.turn_off
                            target: !input "light"
                            data:
                              transition: 1
                    default:
                      - service: light.turn_on
                        target: !input "light"
                        data:
                          transition: 1
            # else double click
            default:
              - service: light.turn_on
                target: !input "light"
                data:
                  transition: 1
                  brightness_pct: 100
# long click
# - conditions:
#     - "{{ endpoint_id == 1 }}"
#     - "{{ cluster_id == 8 }}"
#     - "{{ command == 'move_with_on_off' }}"
#   sequence:
#     - choose:
#       default: !input "button_long"
#     - wait_for_trigger:
#         - platform: event
#           event_type: zha_event
#           event_data:
#             device_id: !input "shortcut_button"
#             endpoint_id: 1
#             cluster_id: 8
#             command: stop
#       timeout:
#         seconds: 10
